#!/usr/bin/env bash
pushd $(dirname $0)
source ./functions.sh
rm $WARN 2> /dev/null
touch $WARN
for path in $(ls $PWD/[0-9]*); do
    $path
done
echo
echo ======================================================
cat $WARN
exit
$0.sshd
$0.users
$0.dnf
