#!/usr/bin/env bash

pushd $(dirname $0) > /dev/null

export PATH=$(dirname $PWD)/bin:${PWD}/bin:${PATH}
export MYTMP=/tmp/my
export MYLOG=/tmp/my/log.$(my.timestamp)
mkdir -p ${MYTMP}
touch ${MYLOG}

for path in $(ls ${PWD}/scripts/[0-9]* | sort); do
    export MYSCRIPT=${path##*/}
    $path
done

echo "==============================================="
cat $MYLOG | grep "WARN\|NOTE\|EXEC"
